version: "3.8"

networks:
       test_network:
              external: true
services:
       db:
              image: mysql
              container_name: mysql1
              restart: always
              ports:
                     - "3306:3306"
              networks:
                     - test_network
              environment:
                     MYSQL_ROOT_PASSWORD: helloworld

       phpmyadmin:
              image: phpmyadmin
              container_name: phpmyadmin1
              links:
                     - db
              ports:
                     - "8082:80"
              networks:
                     - test_network
              environment:
                     PMA_HOST: db
                     PMA_PORT: 3306
              depends_on:
                     - db

