version: "3.8"

networks:
       test_network:
              external: true
services:
       mydb:
              image: mysql
              container_name: mydb1
              restart: always
              ports:
                     - "3306:3306"
              networks:
                     - test_network
              environment:
                     MYSQL_ROOT_PASSWORD: helloworld

       phpmyadmin:
              image: phpmyadmin
              container_name: phpmyadmin1
              links:
                     - mydb
              ports:
                     - "8082:80"
              networks:
                     - test_network
              environment:
                     PMA_HOST: mydb
                     PMA_PORT: 3306
              depends_on:
                     - mydb

       website:
              build: ./website
              container_name: flask-web
              restart: always
              links:
                      - mydb
              ports:
                     - '5400:5400'
              networks:
                      - test_network
              depends_on:
                      - mydb




